[project]
name = "src"
version = "0.0.1"
description = "An MLOps project Referesher"
authors = [{name = "Samarth Khajuria", email = "samkhajuria0@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}